### ISSUE TITLE
grunt-jade-usemin doesn't replace references in jade file

### ISSUE THREAD

**Issue by ThorstenHans** [pgilad/grunt-jade-usemin#4]
I've configured my `jade-usemin` task using this Gruntfile.coffee

```
jadeUsemin:
  main:
    options:
      uglify: true
    files:
      src: 'dist/views/**.jade'
```

my jade file looks like the following

```
 //-<!-- build:css dist/public/styles/foo.min.css -->
 link(rel='stylesheet', href='../bower_components/bootstrap/dist/css/bootstrap.min.css')
 link(rel='stylesheet', href='../public/styles/foo.css')
 //-<!-- endbuild -->
```

It's actually generating the concated and minified file foo.min.css within the right directory. but it didn't replace the `build expression` within the jade files.
Am I missing something. I've reviewed the source but I'm not sure if there is a hook which I'm missing for prepareUsemin or something like that.
